name: builder

on:
  workflow_run:
    workflows: ["ktlint"]
    branches: [lab6]
    types: 
      - completed

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build client jar
        run: gradle :client:fatJar
      - name: build server jar
        run: gradle :server:fatJar
