name: builder

on:
  push

jobs:
  lint:
    uses: ./.github/workflows/linter.yml
  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - name: build client jar
        run: gradle :client:fatJar
      - name: build server jar
        run: gradle :server:fatJar
      - name: deploy client jar to helios
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./client/build/libs/client-1.0-app.jar
          remote: prog/lab6
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
