name: builder

on:
  push

jobs:
  lint:
    uses: ./.github/workflows/linter.yml
  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - name: build client jar
        run: gradle :client:fatJar
      - name: build server jar
        run: gradle :server:fatJar
