name: builder

on:
  push

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - run: gradle init
      - name: build client jar
        run: gradle :client:fatJar
      - name: build server jar
        run: gradle :server:fatJar
