name: builder

on:
  push

jobs:
  lint:
    uses: ./.github/workflows/linter.yml
  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - name: build client jar
        run: gradle :client:fatJar
      - name: build server jar
        run: gradle :server:fatJar
      - name: deploy client jar to helios
        run: scp -P 2222 ./client/build/libs/client-1.0-app.jar s408536@helios.cs.ifmo.ru:.
      - name: deploy server jar to helios
        run: scp -P 2222 ./server/build/libs/server-1.0-app.jar s408536@helios.cs.ifmo.ru:.
