name: deploy

on: 
  push

jobs:
  build:
    uses: ./.github/workflows/builder.yml
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: deploy client jar to helios
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "./client/build/libs/client-1.0-app.jar"
          target: "/prog/lab6/"
      
